version: '2'
services:
  api:
    build: .
    volumes:
      - .:/go/src/github.com/jbielick/boundaries.io
    ports:
      - "3001:3001"
    links:
      - mongo
  mongo:
    build: ./mongo
    volumes:
      - ./mongo:/app
      - db-data:/data/db
    ports:
      - "27017:27017"
volumes:
  db-data:
    driver: local