version: '2'
services:
  api:
    build: .
    command: npm start
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3334:3334"
    links:
      - db
  db:
    image: mongo:3.2
    volumes_from:
      - data
  data:
    image: busybox:latest
    volumes:
      - /data
  dataconsole:
    build: ./data
    volumes:
      - ./data:/data
      - /data/node_modules
    links:
      - db