apiVersion: v1
kind: Service
metadata:
  name: api
  labels:
    name: api
spec:
  type: LoadBalancer
  loadBalancerIP: 23.251.152.234
  ports:
    - name: http
      port: 80
      targetPort: 3334
      protocol: TCP
    - name: https
      port: 443
      targetPort: 3334
      protocol: TCP
  selector:
    name: api

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: api
  labels:
    name: api
spec:
  replicas: 2
  template:
    metadata:
      labels:
        name: api
    spec:
      nodeSelector:
        cloud.google.com/gke-nodepool: default-pool
      containers:
      - name: api
        image: gcr.io/boundariesio/api:ccdd1c2
        ports:
        - containerPort: 3334
        livenessProbe:
          httpGet:
            path: /
            port: 3334
          initialDelaySeconds: 2
          timeoutSeconds: 1
        readinessProbe:
          httpGet:
            path: /
            port: 3334
          initialDelaySeconds: 2
          timeoutSeconds: 1