apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    name: db
spec:
  ports:
    - port: 27017
  selector:
    name: db

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: db
  labels:
    name: db
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: db
    spec:
      nodeSelector:
        cloud.google.com/gke-nodepool: db
      containers:
        - image: mongo:3.0.4
          name: db
          ports:
            - containerPort: 27017
              name: main
          volumeMounts:
              # This name must match the volumes.name below.
            - name: db-data
              mountPath: "/data"
      volumes:
        - name: db-data
          gcePersistentDisk:
            # This disk must already exist.
            pdName: db-data
            fsType: ext4