#!/bin/bash

mongo db/geo --eval \
  "JSON.stringify(db.$1.ensureIndex({geometry: '2dsphere'}) && db.$1.ensureIndex({'$2': 'text'}))"

cat | mongoimport \
	--host db \
  --jsonArray \
  --upsert \
  --upsertFields $2 \
  --collection $1 \
  --db geo